---

- name: stop
  hosts: registry
  vars_files:
    - vars/vars
    - vars/vault
    - vars/common_vars 
    - vars/common_vault
  vars:
    - project_stage_dir: "{{ stage_dir }}/{{ project_id }}/{{ inventory_hostname }}"
  tasks:
    - name: 'stop the registry'
      command: '{{ project_stage_dir }}/docker-compose -f {{ project_stage_dir }}/registry/docker-compose.yaml stop'
    - name: 'remove the registry'
      command: '{{ project_stage_dir }}/docker-compose -f {{ project_stage_dir }}/registry/docker-compose.yaml rm -vf'