version: '2'

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - "{{ registry_port }}:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - {{ staging_area }}/registry/data:/var/lib/registry
      - {{ staging_area }}/registry/certs:/certs
      - {{ staging_area }}/registry/auth:/auth
    container_name: {{ project_id }}
